version: "3.8"
services:
  nodeapp:
    container_name: backend
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    volumes:
      - .:/app
    env_file: .env
    ports:
      - "4000:4000"
    links:
      - db
    depends_on:
      - db
    environment:
      WAIT_HOSTS: db:5432
    networks:
      - node-webapp-network
  db:
    container_name: postgres
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
    networks:
      - node-webapp-network
volumes:
  db:
    driver: local
networks:
  node-webapp-network:
    driver: bridge